name: maestro_just_audio
description: An implementation of maestro package using just_audio.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
dependencies:
  heart:
    git:
      url: https://github.com/Papi-Eruh/heart.git
  just_audio: ^0.10.5
  maestro:
    git:
      url: https://github.com/Papi-Eruh/maestro.git
  pausable_timer: ^3.1.0+3
  rxdart: ^0.28.0
